# Generated by Django 3.0.5 on 2020-07-09 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20200701_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sender',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
