# Generated by Django 3.0.5 on 2020-07-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.TimeField(),
        ),
    ]
