# Generated by Django 3.0.5 on 2020-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200702_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='topic',
            field=models.CharField(default='greeting', max_length=20),
        ),
    ]
